name: excel_worker
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: kuan <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: ^0.6.1+1

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.4
